name: CI/CD Pipeline
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -e .
          pip install pytest

      - name: Test
        run: |
          export PYTHONPATH=$PYTHONPATH:.
          python3 -m pytest

      - name: Docker build and push (if applicable)
        if: github.event_name == 'push' && github.event.pull_request == null
        run: |
          docker build -t $GITHUB_ACTOR/your-docker-image-name .
          docker tag $GITHUB_ACTOR/your-docker-image-name $GITHUB_ACTOR/your-docker-image-name:latest
          docker login -u $GITHUB_ACTOR -p $GITHUB_TOKEN
          docker push $GITHUB_ACTOR/your-docker-image-name:latest